name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nix
        uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: experimental-features = nix-command flakes

      - name: Run checks
        run: nix flake check

      - name: Check formatting
        run: nix develop ./local#check --command treefmt -- . --fail-on-change --no-cache
